### ISSUE TITLE
Unable to download role from github

### ISSUE THREAD

**Issue by mlvnds** [ElaoInfra/elao-role-npm#2]
Hello @AnsibleGalaxyElao, @hyvs, @nervo,

Same as [here](https://github.com/ElaoInfra/ansible-role-npm/issues/1)
**ERROR:**
```
ansible-galaxy install elao.npm
- downloading role 'npm', owned by elao
- downloading role from https://github.com/ElaoInfra/ansible-role-npm/archive/master.tar.gz
 [ERROR]: failed to download the file: HTTP Error 404: Not Found

 [WARNING]: - elao.npm was NOT installed successfully.

ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
```

**FIX:**
```
ansible-galaxy install elao.npm,2.0
- downloading role 'npm', owned by elao
- downloading role from https://github.com/ElaoInfra/ansible-role-npm/archive/2.0.tar.gz
- extracting elao.npm to /etc/ansible/roles/elao.npm
- elao.npm was installed successfully
```

Do you plan to add a master branch or modify the default github reference from ansible galaxy ?
Thanks for your work.

**Comment by gfaivre** [comment]
Hi Melvin,

All of those roles aren't maintained anymore and we strongly encourage you to have a look on our new Ansible stack: https://github.com/manala

Especially those one:
- https://github.com/manala/ansible-role-npm
- https://github.com/manala/ansible-role-yarn

Thanks for the support :)
Guewen
